### ISSUE TITLE
gconcat sobre retorno de funções

### ISSUE THREAD

**Issue by informeai** [jeffotoni/gconcat#2]
Olá tudo bem ✋🏼 
Parabéns pelo pacote @jeffotoni 👍🏼 
Podemos adicionar funcionalidade de concatenação para retorno de funções
vi que não possui...

**Comment by jeffotoni** [comment]
Você está pensando em algo assim ?
 g.Concat( myfunc(), "/", myfunc2())

**Comment by informeai** [comment]
Pode usar os tipos já implementados.
Um exemplo seria como esse:
````
g.Concat("foo", func(int)string,"bar")
````

a função retornaria um valor que seria dos tipos primitivos, e então esse valor seria concatenado com os demais argumentos da `g.Concat`

O que acha jefferson?

**Comment by jeffotoni** [comment]
show, vc quer tentar ? Ou faço por aqui ?

**Comment by informeai** [comment]
> show, vc quer tentar ? Ou faço por aqui ?

Se vc me permitir posso fazer um fork e trabalhar nisso.
To com tempo e ficarei feliz em Godar ☺️ .

**Comment by jeffotoni** [comment]
rapaz olha ai, seria excelente sua contribuição.. manda bala e vai posicionando se precisa de ajuda... 
Quando lançarem o Generics temos que criar a v2, vou trabalhar na v2 em breve antes do lançamento usando go2goplay

**Comment by informeai** [comment]
> rapaz olha ai, seria excelente sua contribuição.. manda bala e vai posicionando se precisa de ajuda...
> Quando lançarem o Generics temos que criar a v2, vou trabalhar na v2 em breve antes do lançamento usando go2goplay

Show, vou iniciar então, e estarei me posicionando caso precise 👍🏼

**Comment by ancogamer** [comment]
Opa, vi pelo email aqui, boa ideia @informeai  !
